# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Corcoran
email: andrew@ajc.la
description: Passionate software developer and systems engineer. Currently systems engineering at Four Winds Interactive. Constantly improving, learning, and teaching others along the way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ajc.la" # the base hostname & protocol for your site
twitter_username: corc
github_username:  corca
stackoverflow_username: "users/4107320/corc"
linkedin_username: "andrewjcorcoran"

# Build settings
markdown: kramdown
timezone: America/Denver
permalink: /:year/:month/:day/:title

kramdown:
  input: GFM